services:
  nginx:
    image: nginx:mainline
    ports:
      - "443:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5099
    image: backend-final
    ports:
      - "5099:5099"

  frontend:
    image: frontend-final
    ports:
      - "5000:5000"