#networks:
#  dev:

services:
  nginx:
    image: nginx:mainline
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
#    networks:
#      - dev

  backend:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5099
    build:
      dockerfile: CodeClash.API/Dockerfile
      context: .
    ports:
      - "5099:5099"
#    networks:
#      - dev

  frontend:
    build:
      context: ./codeclash.frontend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
#    networks:
#      - dev

#  frontend:
#    build:
#      context: ./codeclash.frontend
#      target: development
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    ports:
#      - 5000:5000
#    command: npm run dev

#  database:
#    image: postgres:16.4
#    restart: always
#    environment:
#      POSTGRES_USER: pgadmin
#      POSTGRES_PASSWORD: fragy72JK923
#      POSTGRES_DB: codeclash
#    volumes:
#      - db-data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#
#volumes:
#  db-data: