services:
  codeclash.api:
    image: codeclash
    build:
      context: .
      dockerfile: CodeClash.API/Dockerfile
  
#  database:

#  codeclash.api-1:
#    image: codeclash.api-1
#    build:
#      context: .
#      dockerfile: CodeClash.UserSolutionTest/Dockerfile
