networks:
  dev:

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    environment:
      - ConnectionStrings__DefaultConnection=Host=213.159.194.209;Port=25432;Database=codeclash;Username=pgadmin;Password=fragy72JK923;Include Error Detail=true
    depends_on:
      - backend
      - frontend
    networks:
      - dev

  backend:
    build:
      dockerfile: CodeClash.API/Dockerfile
      context: .
    ports:
      - 6000:6000
      - 6001:6001
    networks:
      - dev

  frontend:
    build:
      context: ./codeclash.frontend
    ports:
      - 5000:5000
    networks:
      - dev

  database:
    image: postgres:16.4
    restart: always
    environment:
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: fragy72JK923
      POSTGRES_DB: codeclash
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data: