# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  backend:
    build:
      context: "C:\\Users\\Maksim Tseshnaty\\Desktop\\Unik\\CodeClash"
      dockerfile: "CodeClash.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CodeClash.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "example:dev"
    ports: []
    volumes:
    - "C:\\Users\\Maksim Tseshnaty\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\Maksim Tseshnaty\\Desktop\\Unik\\CodeClash\\CodeClash.API:/app:rw"
    - "C:\\Users\\Maksim Tseshnaty\\Desktop\\Unik\\CodeClash:/src:rw"
    working_dir: "/app"
