# This is a generated file. Not intended for manual editing.
services:
  backend:
    build:
      context: "C:\\FIIT\\normalProject\\CodeClash"
      dockerfile: "CodeClash.API/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "dotnet"
    - "/app/bin/Debug/net8.0/CodeClash.API.dll"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
    image: "codeclash.api:dev"
    ports: []
    volumes:
    - "C:\\Users\\artem\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\FIIT\\normalProject\\CodeClash\\CodeClash.API:/app:rw"
    - "C:\\FIIT\\normalProject\\CodeClash:/src:rw"
    working_dir: "/app"
